spring.application.name=auth-service
server.port=8080
server.address=0.0.0.0

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.endpoint.health.show-details=always
course.service.url=http://course1:8081
seat.service.url=http://seat1:8082
