spring.application.name=autoscaler-service
server.port=8083
server.address=0.0.0.0
prometheus.base-url=http://localhost:9090

scaling.interval.ms=30000
scaling.requests-per-replica=100.0


sla.tmin=0.2
sla.tmax=2.0
